### PR TITLE
Added Basic Floating Point Components

### PR DESCRIPTION
**Pull request by TChapman500**
Adds a single-precision floating point library ("Single-Precision FP") with adder/subtractor, multiplier, divider, and negator with combined negate and absolute operations.
EDIT:  Components tested and verified via a JAR Library loaded into Logisim Evolution (Holy Cross Edition) v4.0.1.

### CODE REVIEW

**Comment by kevinawalsh** [comment]
This seems fantastic! It might be a little while before I can merge this,
but I look forward to doing it. Would it be okay for me to make this a
standalone jar library? Maybe even as an example bundled and enabled by
default with the installation?

**Comment by TChapman500** [comment]
A standalone JAR library would be fantastic.  Note that when I couldn't figure out how to get Logisim to automatically select the correct class though.
Also, I will probably be changing the library name to "Floating Point" so that I can add the double-precision format to the library as well.

**Comment by TChapman500** [comment]
Here's a standalone library for you.
https://github.com/TChapman500/Floating-Point-Library-for-Logisim

**Comment by kevinawalsh** [comment]
This is great. I just tried it and it works well. I will add a link to your github on the main page. I can also compile and host a jar as well.

**Comment by TChapman500** [comment]
Thanks.  I've provided a Jar in the latest release so you don't need to compile it yourself.
https://github.com/TChapman500/Floating-Point-Library-for-Logisim/releases

**Comment by TChapman500** [comment]
I just realized I forgot to answer your question.  Yes, you may compile and host a jar file.

**Pull request closed without merging**
